
Negative_Sentences = ['Accepting money obligates me'
,'Being rich is a sin'
,'Being super conscious about every single penny is right thing to do'
,'Daddy doesn\'t like me because I spent too much'
,'Everybody is greedy'
,'God must not want me to have money'
,'God wants us to struggle'
,'God wants us to suffer'
,'Getting too much money is greedy'
,'Having too much money makes you evil'
,'Having too much money stops you from being happy'
,'They don\'t deserve to have a lot of money'
,'I always rent; owning a house would be too scary'
,'I am separate from love'
,'I am neither smart nor talented'
,'I can never get ahead'
,'I can\'t have money and free time'
,'I can\'t handle having money'
,'I can\'t have money'
,'I can\'t save anyone'
,'I do not have enough to share or give away'
,'I don\'t deserve to have a lot of money'
,'I don\'t deserve money'
,'I don\'t have any money'
,'I don\'t have enough money'
,'I don\'t know how to make money'
,'I don\'t know what I\'d do, if I had money'
,'I get nervous, when I think about money'
,'I give up when it comes to money'
,'I hate money'
,'I hate thinking about money'
,'I have to do something, other than what I want, to make money'
,'I have to feel guilty for having money'
,'I have to hustle to make money'
,'I have to own my own home to feel secure'
,'I never have enough money'
,'I never want people to know I have so much money because people are really mean to rich people'
,'I really don\'t want money anyway'
,'I spend money on something that breaks I\'m stupid'
,'I want to have a lot of money when I get old, then people will be nice to me'
,'I will never have enough'
,'I would never feel secure if I had to be responsible for much more than a hammock'
,'If I am successful, people will hate me'
,'If I get paid a lot people will find out that I am a fraud'
,'If I have a little more than I need to get by, someone else has to go without'
,'If I have money, I\'ll just lose it anyway'
,'If I have money, I\'ll lose all my friends'
,'If I have money, others won\'t have money'
,'If I have money, people will be after me for money'
,'If I have money, people will be jealous'
,'If I have money, people will just want me for my money'
,'If I make a lot of money, I will be betraying my father who never made much money'
,'If I make a million dollars, I might lose it and then I would feel stupid and hate myself forever'
,'If I spend money, I won\'t have any money'
,'If you were a smart and cute woman you would have married someone with money by now'
,'If you were a smart woman you would be supporting yourself easily by now'
,'If you work hard, you\'ll never be rich anyway'
,'I\'ll never make money'
,'I\'m afraid'
,'I\'m blocked when it comes to money'
,'I\'m broke and stuck'
,'I\'m going broke'
,'I\'m limited when it comes to money'
,'I\'m not destined to have money'
,'I\'m not good enough to have money'
,'I\'m not good with money'
,'I\'m not willing to do what it takes to make money'
,'I\'m not worthy of having money'
,'I\'m poor'
,'I\'m powerless over money'
,'I\'m stuck when it comes to money'
,'It is better to take less than my due and be free from sticky situations'
,'It is better to take less than to be responsible for someone else\'s hardship'
,'It\'s best if I just want enough to get by'
,'It\'s not fair that those people have so much more money that I do'
,'It\'s a hassle having money'
,'It\'s bad to have money'
,'It\'s bad to want money'
,'It\'s filthy being rich'
,'It\'s impossible to make lots of money'
,'It\'s more spiritual being poor'
,'It\'s not spiritual having money'
,'It\'s shameful being rich'
,'It\'s tough times'
,'Making money is a pain'
,'Making money is hard'
,'Money can\'t buy love'
,'Money causes fights about money'
,'Money causes problems'
,'Money causes stress'
,'Money doesn\'t grow on trees'
,'Money is a curse'
,'Money is a pain in the neck'
,'Money is a sin'
,'Money is dirty'
,'Money is frustrating'
,'Money is hard to come by'
,'Money is hard to deal with'
,'Money is hard to get'
,'Money is not spiritual'
,'Money is the root of all evil'
,'Money makes the world go round'
,'Money slips through my hands'
,'Money spoils you'
,'Money will change me for the worse'
,'More money goes out than comes in'
,'My prosperity takes away from someone else\'s prosperity'
,'Never buy anything that you don\'t need'
,'No matter what I do, I won\'t make any money at it'
,'Only some people get to have money'
,'Only a select few get to have money'
,'Other people get to have money, but not me'
,'Poor people suffer more'
,'Rich people are corrupt'
,'Rich people are evil'
,'Rich people are greedy'
,'Rich people are stuck up'
,'Rich people don\'t make it into Heaven'
,'Rich people get there by taking advantage of others'
,'Rich people think they are better than everyone'
,'The economy is poor'
,'The poor get poorer'
,'The rich get richer'
,'There is not enough money to go around'
,'There\'s a shortage of money'
,'There\'s not enough money in the universe'
,'There\'s not enough money to go around'
,'Time is money'
,'To be a valuable person, I have to work more for less money than other people do'
,'To save money you have to do without things'
,'When I think about money, I shut down'
,'Worrying about money is tacky'
,'You can never have enough money'
,'You get what you deserve'
,'You have to break your back to make money'
,'You have to do lots of things you don\'t like in order to have money'
,'You have to sell your soul to have money'
,'You have to struggle to survive'
,'You have to suffer to get close to God'
,'You have to work hard to get it'
,'You have to work hard to have money'
,'You have to work hard, scramble, struggle, suffer, and pursue money'
,'You should always use money well'
,'The love of money is the root of all evil'
,'When it comes to money, more less is better']

Positive_Sentences = [ 'Happiness is my birthright I embrace happiness as my set point state of being'
,' I feel joy and contentment in this moment right now'
,' I awaken in the morning feeling happy and enthusiastic about life'
,' I can tap into a wellspring of inner happiness anytime I wish'
,' By allowing myself to be happy, I inspire others to be happy as well'
,' I have fun with all of my endeavors, even the most mundane'
,' I look at the world around me and can\'t help but smile and feel joy'
,' I find joy and pleasure in the most simple things in life'
,' I have an active sense of humor and love to share laughter with others'
,' My heart is overflowing with joy'
,' I rest in happiness when I go to sleep, knowing all is well in my world'
,' My partner and I share a deep and powerful love for each other'
,' I respect and admire my partner and see the best in him\/her'
,' I love my partner exactly how he/she is and enjoy his/her unique qualities'
,' My partner and I share emotional intimacy daily through talking and touch'
,' I have healthy boundaries with my partner'
,' My partner and I have fun together and find new ways to enjoy our time together'
,' My partner and I communicate openly and resolve conflict peacefully and respectfully'
,' I am able to be fully myself and completely authentic in my love relationship'
,'  I communicate my desires and needs clearly and confidently with my partner'
,' I want the best for my partner and easily go out of my way to support him/her'
,' I expect to be successful in all of my endeavors Success is my natural state'
,' I easily find solutions to challenges and roadblocks and move past them quickly'
,' Mistakes and setbacks are stepping stones to my success because I learn from them'
,' Every day in every way, I am becoming more and more successful'
,' I feel successful with my life right now, even as I work toward future success'
,' I know exactly what I need to do to achieve success'
,' I see fear as the fuel for my success and take bold action in spite of fear'
,' I feel powerful, capable, confident, energetic, and on top of the world'
,' I have an intention for success and know it is a reality awaiting my arrival'
,' I have now reached my goal of _______ and feel the excitement of my achievement'
,' Today I am successful. Tomorrow I will be successful. Every day I am successful'
,' When I breath, I inhale confidence and exhale timidity :P '
,' I love meeting strangers and approach them with boldness and enthusiasm'
,' I live in the present and am confident of the future ;)'
,' My personality exudes confidence I am bold and outgoing B)'
,' I am self-reliant, creative and persistent in whatever I do'
,' I am energetic and enthusiastic Confidence is my second nature'
,' I always attract only the best of circumstances and the best positive people in my life'
,' I am a problem solver I focus on solutions and always find the best solution'
,' I love change and easily adjust myself to new situations'
,' I am well groomed, healthy and full of confidence. My outer self is matched by my inner well being'
,' Self confidence is what I thrive on. Nothing is impossible and life is great :)'
,' I always see only the good in others. I attract only positive confident people'
,' I approve of myself and love myself deeply and completely <3 '
,' I am unique. I feel good about being alive and being me :)'
,' I trust myself and know my inner wisdom is my best guide'
,' I have integrity. I am totally reliable. I do what I say'
,' I act from a place of personal security'
,' I fully accept myself and know that I am worthy of great things in life'
,' I choose to be proud of myself'
,' I find deep inner peace within myself as I am'
,' I fill my mind with positive and nourishing thoughts'
,' My confidence, self esteem, and inner wisdom are increasing with each day'
,' My immune system is very strong and can deal with any kind of bacteria, germs and viruses'
,' Every cell in my body vibrates with energy and health'
,' I am completely pain free, and my body is full of energy'
,' I nourish my body with healthy food'
,' All of my body systems are functioning perfectly'
,' My body is healing, and I feel better and better every day'
,' I enjoy exercising my body and strengthening my muscles'
,' With every breath out, I release stress in my body'
,' I send love and healing to every organ of my body'
,' I breathe deeply, exercise regularly and feed only good nutritious food to my body'
,' I pay attention and listen to what my body needs for health and vitality'
,' I sleep soundly and peacefully, and awaken feeling rested and energetic'
,' I am surrounded by people who encourage and support healthy choices'
,' My world is a peaceful, loving, and joy-filled place to live'
,' I sow the seeds of peace wherever I go'
,' I surround myself with peaceful people'
,' My work environment is calm and peaceful'
,' I breath in peace, I breath out chaos and disorder'
,' My home is a peaceful sanctuary where I feel safe and happy'
,' In all that I say and do, I choose peace'
,' I release past anger and hurts and fill myself with serenity and peaceful thoughts'
,' Peace descends all around me now and always'
,' I send peace from myself into the world'
,' I respond peacefully in all situations'
,' I am grounded in the experience of the present moment'
,' I am focus and engaged in the task at hand'
,' All is well right now'
,' I am grateful for this moment and find joy in it'
,' I gently and easily return to the present moment'
,' I observe my thoughts and actions without judging them'
,' I am fully present in all of my relationships'
,' Life is happening in this moment'
,' I accept and embrace all experiences, even unpleasant ones'
,' I observe my emotions without getting attached to them'
,' I meditate easily without resistance or anxiety'
,' I release the past and live fully in the present moment'
,' Calmness washes over me with every deep breath I take'
,' Every day I am more and more at ease'
,' Being calm and relaxed energizes my whole being'
,' All the muscles in my body are releasing and relaxing'
,' All negativity and stress are evaporating from my body and my mind'
,' I breath in relaxation. I breath out stress'
,' Even when there is chaos around me, I remain calm and centered'
,' I transcend stress of any kind. I live in peace'
,' I am free of anxiety, and a calm inner peace fills my mind and body']












positive = ['This game is so much fun! :D',
            'The weather is nice today. :)',
            'I wish this moment could last forever... :]',
            'I feel like I\'m in heaven. :]',
            'We finally won the match! :D',
            'LOL! This is video is really funny. xD',
            'A nice hot bath after all the work feels so relaxing.',
            'I\'m positive that I\'ll finish the work by noon.',
            'This game\'s too easy. B)',
            'This movie is freaking awesome! :o',
            'You nailed it man!',
            'You look gorgeous.',
            'Dude, you\'ve got killer looks. ;) Good luck for the date.']

negative = ['Man, this work is so tiring. >.<',
            'She punishes me for no reason!',
            'Damn it bro, stop irritating me.',
            'I\'m not satisfied with my marks.',
            'I think I\'m going to hell for this. :|',
            'Not funny bro. Not funny. :|',
            'I feel like I wanna kill you right now.',
            'I wish the whole universe be destroyed now.',
            'You worthless piece of shit! Come here now!',
            'She broke my heart... :( </3',
            'She\'s telling this now? Great! :|',
            'Asking you for a favour is like asking a stone. Better do it myself',
            'Didn\'t your parents teach you to respect your elders?']

